class object {
public:
	void draw (SDL_Renderer* &ren);
	void set_texture (SDL_Renderer* &renderer);
	SDL_Rect        rect;                                   // rectangle for drawing sprite...
	SDL_Rect        tesrect;                                // rectangle for drawing sprite offset...
	SDL_Surface*    surf=SDL_LoadBMP("res/tilemapFFZ.bmp"); // test image...
	SDL_Texture*	text;                                   // texture for rendering things to screen...
};
